package com.bupt.recommender.entity;

import java.io.Serializable;

public class LawCaseIllegalPO implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_illegal2_tf.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_illegal2_tf.DIS_ID
     *
     * @mbggenerated
     */
    private String disId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_illegal2_tf.BUS_PCODE
     *
     * @mbggenerated
     */
    private String busPcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_illegal2_tf.STANDARD_ID
     *
     * @mbggenerated
     */
    private String standardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_illegal2_tf.STANDARD_CODE
     *
     * @mbggenerated
     */
    private String standardCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_illegal2_tf.CREATE_TIME
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_illegal2_tf.ST_OR_ILL
     *
     * @mbggenerated
     */
    private Short stOrIll;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_illegal2_tf.ILL_ID
     *
     * @mbggenerated
     */
    private String illId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_illegal2_tf.FACT_DESC
     *
     * @mbggenerated
     */
    private String factDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_illegal2_tf.FACT_VALUE
     *
     * @mbggenerated
     */
    private String factValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_illegal2_tf.OPINION
     *
     * @mbggenerated
     */
    private String opinion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_illegal2_tf.OPINION_VALUE
     *
     * @mbggenerated
     */
    private String opinionValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_discipline_illegal2_tf
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_illegal2_tf.ID
     *
     * @return the value of t_discipline_illegal2_tf.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_illegal2_tf.ID
     *
     * @param id the value for t_discipline_illegal2_tf.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_illegal2_tf.DIS_ID
     *
     * @return the value of t_discipline_illegal2_tf.DIS_ID
     *
     * @mbggenerated
     */
    public String getDisId() {
        return disId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_illegal2_tf.DIS_ID
     *
     * @param disId the value for t_discipline_illegal2_tf.DIS_ID
     *
     * @mbggenerated
     */
    public void setDisId(String disId) {
        this.disId = disId == null ? null : disId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_illegal2_tf.BUS_PCODE
     *
     * @return the value of t_discipline_illegal2_tf.BUS_PCODE
     *
     * @mbggenerated
     */
    public String getBusPcode() {
        return busPcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_illegal2_tf.BUS_PCODE
     *
     * @param busPcode the value for t_discipline_illegal2_tf.BUS_PCODE
     *
     * @mbggenerated
     */
    public void setBusPcode(String busPcode) {
        this.busPcode = busPcode == null ? null : busPcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_illegal2_tf.STANDARD_ID
     *
     * @return the value of t_discipline_illegal2_tf.STANDARD_ID
     *
     * @mbggenerated
     */
    public String getStandardId() {
        return standardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_illegal2_tf.STANDARD_ID
     *
     * @param standardId the value for t_discipline_illegal2_tf.STANDARD_ID
     *
     * @mbggenerated
     */
    public void setStandardId(String standardId) {
        this.standardId = standardId == null ? null : standardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_illegal2_tf.STANDARD_CODE
     *
     * @return the value of t_discipline_illegal2_tf.STANDARD_CODE
     *
     * @mbggenerated
     */
    public String getStandardCode() {
        return standardCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_illegal2_tf.STANDARD_CODE
     *
     * @param standardCode the value for t_discipline_illegal2_tf.STANDARD_CODE
     *
     * @mbggenerated
     */
    public void setStandardCode(String standardCode) {
        this.standardCode = standardCode == null ? null : standardCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_illegal2_tf.CREATE_TIME
     *
     * @return the value of t_discipline_illegal2_tf.CREATE_TIME
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_illegal2_tf.CREATE_TIME
     *
     * @param createTime the value for t_discipline_illegal2_tf.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_illegal2_tf.ST_OR_ILL
     *
     * @return the value of t_discipline_illegal2_tf.ST_OR_ILL
     *
     * @mbggenerated
     */
    public Short getStOrIll() {
        return stOrIll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_illegal2_tf.ST_OR_ILL
     *
     * @param stOrIll the value for t_discipline_illegal2_tf.ST_OR_ILL
     *
     * @mbggenerated
     */
    public void setStOrIll(Short stOrIll) {
        this.stOrIll = stOrIll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_illegal2_tf.ILL_ID
     *
     * @return the value of t_discipline_illegal2_tf.ILL_ID
     *
     * @mbggenerated
     */
    public String getIllId() {
        return illId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_illegal2_tf.ILL_ID
     *
     * @param illId the value for t_discipline_illegal2_tf.ILL_ID
     *
     * @mbggenerated
     */
    public void setIllId(String illId) {
        this.illId = illId == null ? null : illId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_illegal2_tf.FACT_DESC
     *
     * @return the value of t_discipline_illegal2_tf.FACT_DESC
     *
     * @mbggenerated
     */
    public String getFactDesc() {
        return factDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_illegal2_tf.FACT_DESC
     *
     * @param factDesc the value for t_discipline_illegal2_tf.FACT_DESC
     *
     * @mbggenerated
     */
    public void setFactDesc(String factDesc) {
        this.factDesc = factDesc == null ? null : factDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_illegal2_tf.FACT_VALUE
     *
     * @return the value of t_discipline_illegal2_tf.FACT_VALUE
     *
     * @mbggenerated
     */
    public String getFactValue() {
        return factValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_illegal2_tf.FACT_VALUE
     *
     * @param factValue the value for t_discipline_illegal2_tf.FACT_VALUE
     *
     * @mbggenerated
     */
    public void setFactValue(String factValue) {
        this.factValue = factValue == null ? null : factValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_illegal2_tf.OPINION
     *
     * @return the value of t_discipline_illegal2_tf.OPINION
     *
     * @mbggenerated
     */
    public String getOpinion() {
        return opinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_illegal2_tf.OPINION
     *
     * @param opinion the value for t_discipline_illegal2_tf.OPINION
     *
     * @mbggenerated
     */
    public void setOpinion(String opinion) {
        this.opinion = opinion == null ? null : opinion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_illegal2_tf.OPINION_VALUE
     *
     * @return the value of t_discipline_illegal2_tf.OPINION_VALUE
     *
     * @mbggenerated
     */
    public String getOpinionValue() {
        return opinionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_illegal2_tf.OPINION_VALUE
     *
     * @param opinionValue the value for t_discipline_illegal2_tf.OPINION_VALUE
     *
     * @mbggenerated
     */
    public void setOpinionValue(String opinionValue) {
        this.opinionValue = opinionValue == null ? null : opinionValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discipline_illegal2_tf
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", disId=").append(disId);
        sb.append(", busPcode=").append(busPcode);
        sb.append(", standardId=").append(standardId);
        sb.append(", standardCode=").append(standardCode);
        sb.append(", createTime=").append(createTime);
        sb.append(", stOrIll=").append(stOrIll);
        sb.append(", illId=").append(illId);
        sb.append(", factDesc=").append(factDesc);
        sb.append(", factValue=").append(factValue);
        sb.append(", opinion=").append(opinion);
        sb.append(", opinionValue=").append(opinionValue);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}