package com.bupt.recommender.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class LawCasePO implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.COMP_NO
     *
     * @mbggenerated
     */
    private String compNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.COMP_ID
     *
     * @mbggenerated
     */
    private String compId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.COMP_NAME
     *
     * @mbggenerated
     */
    private String compName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.BUS_PCODE
     *
     * @mbggenerated
     */
    private String busPcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.BUS_CCODE
     *
     * @mbggenerated
     */
    private String busCcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.BUS_ACODE
     *
     * @mbggenerated
     */
    private String busAcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.BUS_TCODE
     *
     * @mbggenerated
     */
    private String busTcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.OCODE
     *
     * @mbggenerated
     */
    private String ocode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.ECONOMIC_CODE
     *
     * @mbggenerated
     */
    private String economicCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.PRINCIPAL
     *
     * @mbggenerated
     */
    private String principal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.CARD_TYPE
     *
     * @mbggenerated
     */
    private String cardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.IDCARD
     *
     * @mbggenerated
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.DIS_ID
     *
     * @mbggenerated
     */
    private String disId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.REPORT_NUM
     *
     * @mbggenerated
     */
    private Short reportNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.SPECIALTY_PRIMARY
     *
     * @mbggenerated
     */
    private String specialtyPrimary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.SPECIALTY_SECONDARY
     *
     * @mbggenerated
     */
    private String specialtySecondary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.SPE_PRI
     *
     * @mbggenerated
     */
    private String spePri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.DISCIPLINE_SOURCE
     *
     * @mbggenerated
     */
    private String disciplineSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.IS_REGULAR
     *
     * @mbggenerated
     */
    private String isRegular;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.REGULAR_ID
     *
     * @mbggenerated
     */
    private String regularId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.PUNISHIMENTPROCEDURE
     *
     * @mbggenerated
     */
    private String punishimentprocedure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.HEARING
     *
     * @mbggenerated
     */
    private String hearing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.RECORD_DATE
     *
     * @mbggenerated
     */
    private String recordDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.DECISION_DATE
     *
     * @mbggenerated
     */
    private String decisionDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.DOCUMENT_NO
     *
     * @mbggenerated
     */
    private String documentNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.LIC_REGION
     *
     * @mbggenerated
     */
    private String licRegion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.LIC_UALSCXAX
     *
     * @mbggenerated
     */
    private String licUalscxax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.LIC_SPE
     *
     * @mbggenerated
     */
    private String licSpe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.LIC_YEAR
     *
     * @mbggenerated
     */
    private String licYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.LIC_NUM
     *
     * @mbggenerated
     */
    private String licNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.ALLOW_ORG
     *
     * @mbggenerated
     */
    private String allowOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.ALLOW_SUP_ORG
     *
     * @mbggenerated
     */
    private String allowSupOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.A_REVIEW
     *
     * @mbggenerated
     */
    private String aReview;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.A_REVIEW_DATE
     *
     * @mbggenerated
     */
    private String aReviewDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.A_LITIGATION
     *
     * @mbggenerated
     */
    private String aLitigation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.A_LITIGATION_DATE
     *
     * @mbggenerated
     */
    private String aLitigationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.UNPUNISH
     *
     * @mbggenerated
     */
    private String unpunish;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.FIXED_PLACE
     *
     * @mbggenerated
     */
    private String fixedPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.PUNISHED_TIMES
     *
     * @mbggenerated
     */
    private Integer punishedTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.CONTROL_TIMES
     *
     * @mbggenerated
     */
    private Integer controlTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.PERFORM_STATUS
     *
     * @mbggenerated
     */
    private String performStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.PERFORM_RESULT
     *
     * @mbggenerated
     */
    private String performResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.ACTUAL_PENALTY
     *
     * @mbggenerated
     */
    private BigDecimal actualPenalty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.CLOSED_DATE
     *
     * @mbggenerated
     */
    private String closedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.NO_LICENSE
     *
     * @mbggenerated
     */
    private Short noLicense;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.DATA_TYPE
     *
     * @mbggenerated
     */
    private String dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.IS_ALTER
     *
     * @mbggenerated
     */
    private Short isAlter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.R_ORGCODE
     *
     * @mbggenerated
     */
    private String rOrgcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.R_ORGNAME
     *
     * @mbggenerated
     */
    private String rOrgname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.R_HEAD
     *
     * @mbggenerated
     */
    private String rHead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.R_DEPTNAME
     *
     * @mbggenerated
     */
    private String rDeptname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.R_DEPTCODE
     *
     * @mbggenerated
     */
    private String rDeptcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.R_NAME
     *
     * @mbggenerated
     */
    private String rName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.R_ID
     *
     * @mbggenerated
     */
    private String rId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.R_DATE
     *
     * @mbggenerated
     */
    private String rDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.CREATE_TIME
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.UPDATE_TIME
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.IS_DELETE
     *
     * @mbggenerated
     */
    private Short isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.DELETE_TIME
     *
     * @mbggenerated
     */
    private String deleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.AUDIT_USERID
     *
     * @mbggenerated
     */
    private String auditUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.AUDIT_USERNAME
     *
     * @mbggenerated
     */
    private String auditUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.AUDIT_TIME
     *
     * @mbggenerated
     */
    private String auditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.LAST_USERID
     *
     * @mbggenerated
     */
    private String lastUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.LAST_USERNAME
     *
     * @mbggenerated
     */
    private String lastUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.TRAN_STATE
     *
     * @mbggenerated
     */
    private Short tranState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.TRANSFER
     *
     * @mbggenerated
     */
    private Short transfer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.CREDIT_CODE
     *
     * @mbggenerated
     */
    private String creditCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.ADD_PUN
     *
     * @mbggenerated
     */
    private Short addPun;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.ADD_PUN_PENALTY
     *
     * @mbggenerated
     */
    private BigDecimal addPunPenalty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.SINGLE_NO
     *
     * @mbggenerated
     */
    private String singleNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.IS_DETECTION
     *
     * @mbggenerated
     */
    private String isDetection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.DETECTION_ID
     *
     * @mbggenerated
     */
    private String detectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.REG_ADDR
     *
     * @mbggenerated
     */
    private String regAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.BUS_ADDR
     *
     * @mbggenerated
     */
    private String busAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.DIS_NAME
     *
     * @mbggenerated
     */
    private String disName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline_tf.PUNISHIMENTBASIS
     *
     * @mbggenerated
     */
    private String punishimentbasis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_discipline_tf
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.ID
     *
     * @return the value of t_discipline_tf.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.ID
     *
     * @param id the value for t_discipline_tf.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.COMP_NO
     *
     * @return the value of t_discipline_tf.COMP_NO
     *
     * @mbggenerated
     */
    public String getCompNo() {
        return compNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.COMP_NO
     *
     * @param compNo the value for t_discipline_tf.COMP_NO
     *
     * @mbggenerated
     */
    public void setCompNo(String compNo) {
        this.compNo = compNo == null ? null : compNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.COMP_ID
     *
     * @return the value of t_discipline_tf.COMP_ID
     *
     * @mbggenerated
     */
    public String getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.COMP_ID
     *
     * @param compId the value for t_discipline_tf.COMP_ID
     *
     * @mbggenerated
     */
    public void setCompId(String compId) {
        this.compId = compId == null ? null : compId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.COMP_NAME
     *
     * @return the value of t_discipline_tf.COMP_NAME
     *
     * @mbggenerated
     */
    public String getCompName() {
        return compName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.COMP_NAME
     *
     * @param compName the value for t_discipline_tf.COMP_NAME
     *
     * @mbggenerated
     */
    public void setCompName(String compName) {
        this.compName = compName == null ? null : compName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.BUS_PCODE
     *
     * @return the value of t_discipline_tf.BUS_PCODE
     *
     * @mbggenerated
     */
    public String getBusPcode() {
        return busPcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.BUS_PCODE
     *
     * @param busPcode the value for t_discipline_tf.BUS_PCODE
     *
     * @mbggenerated
     */
    public void setBusPcode(String busPcode) {
        this.busPcode = busPcode == null ? null : busPcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.BUS_CCODE
     *
     * @return the value of t_discipline_tf.BUS_CCODE
     *
     * @mbggenerated
     */
    public String getBusCcode() {
        return busCcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.BUS_CCODE
     *
     * @param busCcode the value for t_discipline_tf.BUS_CCODE
     *
     * @mbggenerated
     */
    public void setBusCcode(String busCcode) {
        this.busCcode = busCcode == null ? null : busCcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.BUS_ACODE
     *
     * @return the value of t_discipline_tf.BUS_ACODE
     *
     * @mbggenerated
     */
    public String getBusAcode() {
        return busAcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.BUS_ACODE
     *
     * @param busAcode the value for t_discipline_tf.BUS_ACODE
     *
     * @mbggenerated
     */
    public void setBusAcode(String busAcode) {
        this.busAcode = busAcode == null ? null : busAcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.BUS_TCODE
     *
     * @return the value of t_discipline_tf.BUS_TCODE
     *
     * @mbggenerated
     */
    public String getBusTcode() {
        return busTcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.BUS_TCODE
     *
     * @param busTcode the value for t_discipline_tf.BUS_TCODE
     *
     * @mbggenerated
     */
    public void setBusTcode(String busTcode) {
        this.busTcode = busTcode == null ? null : busTcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.OCODE
     *
     * @return the value of t_discipline_tf.OCODE
     *
     * @mbggenerated
     */
    public String getOcode() {
        return ocode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.OCODE
     *
     * @param ocode the value for t_discipline_tf.OCODE
     *
     * @mbggenerated
     */
    public void setOcode(String ocode) {
        this.ocode = ocode == null ? null : ocode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.ECONOMIC_CODE
     *
     * @return the value of t_discipline_tf.ECONOMIC_CODE
     *
     * @mbggenerated
     */
    public String getEconomicCode() {
        return economicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.ECONOMIC_CODE
     *
     * @param economicCode the value for t_discipline_tf.ECONOMIC_CODE
     *
     * @mbggenerated
     */
    public void setEconomicCode(String economicCode) {
        this.economicCode = economicCode == null ? null : economicCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.PRINCIPAL
     *
     * @return the value of t_discipline_tf.PRINCIPAL
     *
     * @mbggenerated
     */
    public String getPrincipal() {
        return principal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.PRINCIPAL
     *
     * @param principal the value for t_discipline_tf.PRINCIPAL
     *
     * @mbggenerated
     */
    public void setPrincipal(String principal) {
        this.principal = principal == null ? null : principal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.CARD_TYPE
     *
     * @return the value of t_discipline_tf.CARD_TYPE
     *
     * @mbggenerated
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.CARD_TYPE
     *
     * @param cardType the value for t_discipline_tf.CARD_TYPE
     *
     * @mbggenerated
     */
    public void setCardType(String cardType) {
        this.cardType = cardType == null ? null : cardType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.IDCARD
     *
     * @return the value of t_discipline_tf.IDCARD
     *
     * @mbggenerated
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.IDCARD
     *
     * @param idcard the value for t_discipline_tf.IDCARD
     *
     * @mbggenerated
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.DIS_ID
     *
     * @return the value of t_discipline_tf.DIS_ID
     *
     * @mbggenerated
     */
    public String getDisId() {
        return disId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.DIS_ID
     *
     * @param disId the value for t_discipline_tf.DIS_ID
     *
     * @mbggenerated
     */
    public void setDisId(String disId) {
        this.disId = disId == null ? null : disId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.REPORT_NUM
     *
     * @return the value of t_discipline_tf.REPORT_NUM
     *
     * @mbggenerated
     */
    public Short getReportNum() {
        return reportNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.REPORT_NUM
     *
     * @param reportNum the value for t_discipline_tf.REPORT_NUM
     *
     * @mbggenerated
     */
    public void setReportNum(Short reportNum) {
        this.reportNum = reportNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.SPECIALTY_PRIMARY
     *
     * @return the value of t_discipline_tf.SPECIALTY_PRIMARY
     *
     * @mbggenerated
     */
    public String getSpecialtyPrimary() {
        return specialtyPrimary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.SPECIALTY_PRIMARY
     *
     * @param specialtyPrimary the value for t_discipline_tf.SPECIALTY_PRIMARY
     *
     * @mbggenerated
     */
    public void setSpecialtyPrimary(String specialtyPrimary) {
        this.specialtyPrimary = specialtyPrimary == null ? null : specialtyPrimary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.SPECIALTY_SECONDARY
     *
     * @return the value of t_discipline_tf.SPECIALTY_SECONDARY
     *
     * @mbggenerated
     */
    public String getSpecialtySecondary() {
        return specialtySecondary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.SPECIALTY_SECONDARY
     *
     * @param specialtySecondary the value for t_discipline_tf.SPECIALTY_SECONDARY
     *
     * @mbggenerated
     */
    public void setSpecialtySecondary(String specialtySecondary) {
        this.specialtySecondary = specialtySecondary == null ? null : specialtySecondary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.SPE_PRI
     *
     * @return the value of t_discipline_tf.SPE_PRI
     *
     * @mbggenerated
     */
    public String getSpePri() {
        return spePri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.SPE_PRI
     *
     * @param spePri the value for t_discipline_tf.SPE_PRI
     *
     * @mbggenerated
     */
    public void setSpePri(String spePri) {
        this.spePri = spePri == null ? null : spePri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.DISCIPLINE_SOURCE
     *
     * @return the value of t_discipline_tf.DISCIPLINE_SOURCE
     *
     * @mbggenerated
     */
    public String getDisciplineSource() {
        return disciplineSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.DISCIPLINE_SOURCE
     *
     * @param disciplineSource the value for t_discipline_tf.DISCIPLINE_SOURCE
     *
     * @mbggenerated
     */
    public void setDisciplineSource(String disciplineSource) {
        this.disciplineSource = disciplineSource == null ? null : disciplineSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.IS_REGULAR
     *
     * @return the value of t_discipline_tf.IS_REGULAR
     *
     * @mbggenerated
     */
    public String getIsRegular() {
        return isRegular;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.IS_REGULAR
     *
     * @param isRegular the value for t_discipline_tf.IS_REGULAR
     *
     * @mbggenerated
     */
    public void setIsRegular(String isRegular) {
        this.isRegular = isRegular == null ? null : isRegular.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.REGULAR_ID
     *
     * @return the value of t_discipline_tf.REGULAR_ID
     *
     * @mbggenerated
     */
    public String getRegularId() {
        return regularId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.REGULAR_ID
     *
     * @param regularId the value for t_discipline_tf.REGULAR_ID
     *
     * @mbggenerated
     */
    public void setRegularId(String regularId) {
        this.regularId = regularId == null ? null : regularId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.PUNISHIMENTPROCEDURE
     *
     * @return the value of t_discipline_tf.PUNISHIMENTPROCEDURE
     *
     * @mbggenerated
     */
    public String getPunishimentprocedure() {
        return punishimentprocedure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.PUNISHIMENTPROCEDURE
     *
     * @param punishimentprocedure the value for t_discipline_tf.PUNISHIMENTPROCEDURE
     *
     * @mbggenerated
     */
    public void setPunishimentprocedure(String punishimentprocedure) {
        this.punishimentprocedure = punishimentprocedure == null ? null : punishimentprocedure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.HEARING
     *
     * @return the value of t_discipline_tf.HEARING
     *
     * @mbggenerated
     */
    public String getHearing() {
        return hearing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.HEARING
     *
     * @param hearing the value for t_discipline_tf.HEARING
     *
     * @mbggenerated
     */
    public void setHearing(String hearing) {
        this.hearing = hearing == null ? null : hearing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.RECORD_DATE
     *
     * @return the value of t_discipline_tf.RECORD_DATE
     *
     * @mbggenerated
     */
    public String getRecordDate() {
        return recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.RECORD_DATE
     *
     * @param recordDate the value for t_discipline_tf.RECORD_DATE
     *
     * @mbggenerated
     */
    public void setRecordDate(String recordDate) {
        this.recordDate = recordDate == null ? null : recordDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.DECISION_DATE
     *
     * @return the value of t_discipline_tf.DECISION_DATE
     *
     * @mbggenerated
     */
    public String getDecisionDate() {
        return decisionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.DECISION_DATE
     *
     * @param decisionDate the value for t_discipline_tf.DECISION_DATE
     *
     * @mbggenerated
     */
    public void setDecisionDate(String decisionDate) {
        this.decisionDate = decisionDate == null ? null : decisionDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.DOCUMENT_NO
     *
     * @return the value of t_discipline_tf.DOCUMENT_NO
     *
     * @mbggenerated
     */
    public String getDocumentNo() {
        return documentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.DOCUMENT_NO
     *
     * @param documentNo the value for t_discipline_tf.DOCUMENT_NO
     *
     * @mbggenerated
     */
    public void setDocumentNo(String documentNo) {
        this.documentNo = documentNo == null ? null : documentNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.LIC_REGION
     *
     * @return the value of t_discipline_tf.LIC_REGION
     *
     * @mbggenerated
     */
    public String getLicRegion() {
        return licRegion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.LIC_REGION
     *
     * @param licRegion the value for t_discipline_tf.LIC_REGION
     *
     * @mbggenerated
     */
    public void setLicRegion(String licRegion) {
        this.licRegion = licRegion == null ? null : licRegion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.LIC_UALSCXAX
     *
     * @return the value of t_discipline_tf.LIC_UALSCXAX
     *
     * @mbggenerated
     */
    public String getLicUalscxax() {
        return licUalscxax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.LIC_UALSCXAX
     *
     * @param licUalscxax the value for t_discipline_tf.LIC_UALSCXAX
     *
     * @mbggenerated
     */
    public void setLicUalscxax(String licUalscxax) {
        this.licUalscxax = licUalscxax == null ? null : licUalscxax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.LIC_SPE
     *
     * @return the value of t_discipline_tf.LIC_SPE
     *
     * @mbggenerated
     */
    public String getLicSpe() {
        return licSpe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.LIC_SPE
     *
     * @param licSpe the value for t_discipline_tf.LIC_SPE
     *
     * @mbggenerated
     */
    public void setLicSpe(String licSpe) {
        this.licSpe = licSpe == null ? null : licSpe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.LIC_YEAR
     *
     * @return the value of t_discipline_tf.LIC_YEAR
     *
     * @mbggenerated
     */
    public String getLicYear() {
        return licYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.LIC_YEAR
     *
     * @param licYear the value for t_discipline_tf.LIC_YEAR
     *
     * @mbggenerated
     */
    public void setLicYear(String licYear) {
        this.licYear = licYear == null ? null : licYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.LIC_NUM
     *
     * @return the value of t_discipline_tf.LIC_NUM
     *
     * @mbggenerated
     */
    public String getLicNum() {
        return licNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.LIC_NUM
     *
     * @param licNum the value for t_discipline_tf.LIC_NUM
     *
     * @mbggenerated
     */
    public void setLicNum(String licNum) {
        this.licNum = licNum == null ? null : licNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.ALLOW_ORG
     *
     * @return the value of t_discipline_tf.ALLOW_ORG
     *
     * @mbggenerated
     */
    public String getAllowOrg() {
        return allowOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.ALLOW_ORG
     *
     * @param allowOrg the value for t_discipline_tf.ALLOW_ORG
     *
     * @mbggenerated
     */
    public void setAllowOrg(String allowOrg) {
        this.allowOrg = allowOrg == null ? null : allowOrg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.ALLOW_SUP_ORG
     *
     * @return the value of t_discipline_tf.ALLOW_SUP_ORG
     *
     * @mbggenerated
     */
    public String getAllowSupOrg() {
        return allowSupOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.ALLOW_SUP_ORG
     *
     * @param allowSupOrg the value for t_discipline_tf.ALLOW_SUP_ORG
     *
     * @mbggenerated
     */
    public void setAllowSupOrg(String allowSupOrg) {
        this.allowSupOrg = allowSupOrg == null ? null : allowSupOrg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.A_REVIEW
     *
     * @return the value of t_discipline_tf.A_REVIEW
     *
     * @mbggenerated
     */
    public String getaReview() {
        return aReview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.A_REVIEW
     *
     * @param aReview the value for t_discipline_tf.A_REVIEW
     *
     * @mbggenerated
     */
    public void setaReview(String aReview) {
        this.aReview = aReview == null ? null : aReview.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.A_REVIEW_DATE
     *
     * @return the value of t_discipline_tf.A_REVIEW_DATE
     *
     * @mbggenerated
     */
    public String getaReviewDate() {
        return aReviewDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.A_REVIEW_DATE
     *
     * @param aReviewDate the value for t_discipline_tf.A_REVIEW_DATE
     *
     * @mbggenerated
     */
    public void setaReviewDate(String aReviewDate) {
        this.aReviewDate = aReviewDate == null ? null : aReviewDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.A_LITIGATION
     *
     * @return the value of t_discipline_tf.A_LITIGATION
     *
     * @mbggenerated
     */
    public String getaLitigation() {
        return aLitigation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.A_LITIGATION
     *
     * @param aLitigation the value for t_discipline_tf.A_LITIGATION
     *
     * @mbggenerated
     */
    public void setaLitigation(String aLitigation) {
        this.aLitigation = aLitigation == null ? null : aLitigation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.A_LITIGATION_DATE
     *
     * @return the value of t_discipline_tf.A_LITIGATION_DATE
     *
     * @mbggenerated
     */
    public String getaLitigationDate() {
        return aLitigationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.A_LITIGATION_DATE
     *
     * @param aLitigationDate the value for t_discipline_tf.A_LITIGATION_DATE
     *
     * @mbggenerated
     */
    public void setaLitigationDate(String aLitigationDate) {
        this.aLitigationDate = aLitigationDate == null ? null : aLitigationDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.UNPUNISH
     *
     * @return the value of t_discipline_tf.UNPUNISH
     *
     * @mbggenerated
     */
    public String getUnpunish() {
        return unpunish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.UNPUNISH
     *
     * @param unpunish the value for t_discipline_tf.UNPUNISH
     *
     * @mbggenerated
     */
    public void setUnpunish(String unpunish) {
        this.unpunish = unpunish == null ? null : unpunish.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.FIXED_PLACE
     *
     * @return the value of t_discipline_tf.FIXED_PLACE
     *
     * @mbggenerated
     */
    public String getFixedPlace() {
        return fixedPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.FIXED_PLACE
     *
     * @param fixedPlace the value for t_discipline_tf.FIXED_PLACE
     *
     * @mbggenerated
     */
    public void setFixedPlace(String fixedPlace) {
        this.fixedPlace = fixedPlace == null ? null : fixedPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.PUNISHED_TIMES
     *
     * @return the value of t_discipline_tf.PUNISHED_TIMES
     *
     * @mbggenerated
     */
    public Integer getPunishedTimes() {
        return punishedTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.PUNISHED_TIMES
     *
     * @param punishedTimes the value for t_discipline_tf.PUNISHED_TIMES
     *
     * @mbggenerated
     */
    public void setPunishedTimes(Integer punishedTimes) {
        this.punishedTimes = punishedTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.CONTROL_TIMES
     *
     * @return the value of t_discipline_tf.CONTROL_TIMES
     *
     * @mbggenerated
     */
    public Integer getControlTimes() {
        return controlTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.CONTROL_TIMES
     *
     * @param controlTimes the value for t_discipline_tf.CONTROL_TIMES
     *
     * @mbggenerated
     */
    public void setControlTimes(Integer controlTimes) {
        this.controlTimes = controlTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.PERFORM_STATUS
     *
     * @return the value of t_discipline_tf.PERFORM_STATUS
     *
     * @mbggenerated
     */
    public String getPerformStatus() {
        return performStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.PERFORM_STATUS
     *
     * @param performStatus the value for t_discipline_tf.PERFORM_STATUS
     *
     * @mbggenerated
     */
    public void setPerformStatus(String performStatus) {
        this.performStatus = performStatus == null ? null : performStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.PERFORM_RESULT
     *
     * @return the value of t_discipline_tf.PERFORM_RESULT
     *
     * @mbggenerated
     */
    public String getPerformResult() {
        return performResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.PERFORM_RESULT
     *
     * @param performResult the value for t_discipline_tf.PERFORM_RESULT
     *
     * @mbggenerated
     */
    public void setPerformResult(String performResult) {
        this.performResult = performResult == null ? null : performResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.ACTUAL_PENALTY
     *
     * @return the value of t_discipline_tf.ACTUAL_PENALTY
     *
     * @mbggenerated
     */
    public BigDecimal getActualPenalty() {
        return actualPenalty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.ACTUAL_PENALTY
     *
     * @param actualPenalty the value for t_discipline_tf.ACTUAL_PENALTY
     *
     * @mbggenerated
     */
    public void setActualPenalty(BigDecimal actualPenalty) {
        this.actualPenalty = actualPenalty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.CLOSED_DATE
     *
     * @return the value of t_discipline_tf.CLOSED_DATE
     *
     * @mbggenerated
     */
    public String getClosedDate() {
        return closedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.CLOSED_DATE
     *
     * @param closedDate the value for t_discipline_tf.CLOSED_DATE
     *
     * @mbggenerated
     */
    public void setClosedDate(String closedDate) {
        this.closedDate = closedDate == null ? null : closedDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.NO_LICENSE
     *
     * @return the value of t_discipline_tf.NO_LICENSE
     *
     * @mbggenerated
     */
    public Short getNoLicense() {
        return noLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.NO_LICENSE
     *
     * @param noLicense the value for t_discipline_tf.NO_LICENSE
     *
     * @mbggenerated
     */
    public void setNoLicense(Short noLicense) {
        this.noLicense = noLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.DATA_TYPE
     *
     * @return the value of t_discipline_tf.DATA_TYPE
     *
     * @mbggenerated
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.DATA_TYPE
     *
     * @param dataType the value for t_discipline_tf.DATA_TYPE
     *
     * @mbggenerated
     */
    public void setDataType(String dataType) {
        this.dataType = dataType == null ? null : dataType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.IS_ALTER
     *
     * @return the value of t_discipline_tf.IS_ALTER
     *
     * @mbggenerated
     */
    public Short getIsAlter() {
        return isAlter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.IS_ALTER
     *
     * @param isAlter the value for t_discipline_tf.IS_ALTER
     *
     * @mbggenerated
     */
    public void setIsAlter(Short isAlter) {
        this.isAlter = isAlter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.R_ORGCODE
     *
     * @return the value of t_discipline_tf.R_ORGCODE
     *
     * @mbggenerated
     */
    public String getrOrgcode() {
        return rOrgcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.R_ORGCODE
     *
     * @param rOrgcode the value for t_discipline_tf.R_ORGCODE
     *
     * @mbggenerated
     */
    public void setrOrgcode(String rOrgcode) {
        this.rOrgcode = rOrgcode == null ? null : rOrgcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.R_ORGNAME
     *
     * @return the value of t_discipline_tf.R_ORGNAME
     *
     * @mbggenerated
     */
    public String getrOrgname() {
        return rOrgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.R_ORGNAME
     *
     * @param rOrgname the value for t_discipline_tf.R_ORGNAME
     *
     * @mbggenerated
     */
    public void setrOrgname(String rOrgname) {
        this.rOrgname = rOrgname == null ? null : rOrgname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.R_HEAD
     *
     * @return the value of t_discipline_tf.R_HEAD
     *
     * @mbggenerated
     */
    public String getrHead() {
        return rHead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.R_HEAD
     *
     * @param rHead the value for t_discipline_tf.R_HEAD
     *
     * @mbggenerated
     */
    public void setrHead(String rHead) {
        this.rHead = rHead == null ? null : rHead.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.R_DEPTNAME
     *
     * @return the value of t_discipline_tf.R_DEPTNAME
     *
     * @mbggenerated
     */
    public String getrDeptname() {
        return rDeptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.R_DEPTNAME
     *
     * @param rDeptname the value for t_discipline_tf.R_DEPTNAME
     *
     * @mbggenerated
     */
    public void setrDeptname(String rDeptname) {
        this.rDeptname = rDeptname == null ? null : rDeptname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.R_DEPTCODE
     *
     * @return the value of t_discipline_tf.R_DEPTCODE
     *
     * @mbggenerated
     */
    public String getrDeptcode() {
        return rDeptcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.R_DEPTCODE
     *
     * @param rDeptcode the value for t_discipline_tf.R_DEPTCODE
     *
     * @mbggenerated
     */
    public void setrDeptcode(String rDeptcode) {
        this.rDeptcode = rDeptcode == null ? null : rDeptcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.R_NAME
     *
     * @return the value of t_discipline_tf.R_NAME
     *
     * @mbggenerated
     */
    public String getrName() {
        return rName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.R_NAME
     *
     * @param rName the value for t_discipline_tf.R_NAME
     *
     * @mbggenerated
     */
    public void setrName(String rName) {
        this.rName = rName == null ? null : rName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.R_ID
     *
     * @return the value of t_discipline_tf.R_ID
     *
     * @mbggenerated
     */
    public String getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.R_ID
     *
     * @param rId the value for t_discipline_tf.R_ID
     *
     * @mbggenerated
     */
    public void setrId(String rId) {
        this.rId = rId == null ? null : rId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.R_DATE
     *
     * @return the value of t_discipline_tf.R_DATE
     *
     * @mbggenerated
     */
    public String getrDate() {
        return rDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.R_DATE
     *
     * @param rDate the value for t_discipline_tf.R_DATE
     *
     * @mbggenerated
     */
    public void setrDate(String rDate) {
        this.rDate = rDate == null ? null : rDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.CREATE_TIME
     *
     * @return the value of t_discipline_tf.CREATE_TIME
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.CREATE_TIME
     *
     * @param createTime the value for t_discipline_tf.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.UPDATE_TIME
     *
     * @return the value of t_discipline_tf.UPDATE_TIME
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.UPDATE_TIME
     *
     * @param updateTime the value for t_discipline_tf.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.IS_DELETE
     *
     * @return the value of t_discipline_tf.IS_DELETE
     *
     * @mbggenerated
     */
    public Short getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.IS_DELETE
     *
     * @param isDelete the value for t_discipline_tf.IS_DELETE
     *
     * @mbggenerated
     */
    public void setIsDelete(Short isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.DELETE_TIME
     *
     * @return the value of t_discipline_tf.DELETE_TIME
     *
     * @mbggenerated
     */
    public String getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.DELETE_TIME
     *
     * @param deleteTime the value for t_discipline_tf.DELETE_TIME
     *
     * @mbggenerated
     */
    public void setDeleteTime(String deleteTime) {
        this.deleteTime = deleteTime == null ? null : deleteTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.AUDIT_USERID
     *
     * @return the value of t_discipline_tf.AUDIT_USERID
     *
     * @mbggenerated
     */
    public String getAuditUserid() {
        return auditUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.AUDIT_USERID
     *
     * @param auditUserid the value for t_discipline_tf.AUDIT_USERID
     *
     * @mbggenerated
     */
    public void setAuditUserid(String auditUserid) {
        this.auditUserid = auditUserid == null ? null : auditUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.AUDIT_USERNAME
     *
     * @return the value of t_discipline_tf.AUDIT_USERNAME
     *
     * @mbggenerated
     */
    public String getAuditUsername() {
        return auditUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.AUDIT_USERNAME
     *
     * @param auditUsername the value for t_discipline_tf.AUDIT_USERNAME
     *
     * @mbggenerated
     */
    public void setAuditUsername(String auditUsername) {
        this.auditUsername = auditUsername == null ? null : auditUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.AUDIT_TIME
     *
     * @return the value of t_discipline_tf.AUDIT_TIME
     *
     * @mbggenerated
     */
    public String getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.AUDIT_TIME
     *
     * @param auditTime the value for t_discipline_tf.AUDIT_TIME
     *
     * @mbggenerated
     */
    public void setAuditTime(String auditTime) {
        this.auditTime = auditTime == null ? null : auditTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.LAST_USERID
     *
     * @return the value of t_discipline_tf.LAST_USERID
     *
     * @mbggenerated
     */
    public String getLastUserid() {
        return lastUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.LAST_USERID
     *
     * @param lastUserid the value for t_discipline_tf.LAST_USERID
     *
     * @mbggenerated
     */
    public void setLastUserid(String lastUserid) {
        this.lastUserid = lastUserid == null ? null : lastUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.LAST_USERNAME
     *
     * @return the value of t_discipline_tf.LAST_USERNAME
     *
     * @mbggenerated
     */
    public String getLastUsername() {
        return lastUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.LAST_USERNAME
     *
     * @param lastUsername the value for t_discipline_tf.LAST_USERNAME
     *
     * @mbggenerated
     */
    public void setLastUsername(String lastUsername) {
        this.lastUsername = lastUsername == null ? null : lastUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.TRAN_STATE
     *
     * @return the value of t_discipline_tf.TRAN_STATE
     *
     * @mbggenerated
     */
    public Short getTranState() {
        return tranState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.TRAN_STATE
     *
     * @param tranState the value for t_discipline_tf.TRAN_STATE
     *
     * @mbggenerated
     */
    public void setTranState(Short tranState) {
        this.tranState = tranState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.TRANSFER
     *
     * @return the value of t_discipline_tf.TRANSFER
     *
     * @mbggenerated
     */
    public Short getTransfer() {
        return transfer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.TRANSFER
     *
     * @param transfer the value for t_discipline_tf.TRANSFER
     *
     * @mbggenerated
     */
    public void setTransfer(Short transfer) {
        this.transfer = transfer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.CREDIT_CODE
     *
     * @return the value of t_discipline_tf.CREDIT_CODE
     *
     * @mbggenerated
     */
    public String getCreditCode() {
        return creditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.CREDIT_CODE
     *
     * @param creditCode the value for t_discipline_tf.CREDIT_CODE
     *
     * @mbggenerated
     */
    public void setCreditCode(String creditCode) {
        this.creditCode = creditCode == null ? null : creditCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.ADD_PUN
     *
     * @return the value of t_discipline_tf.ADD_PUN
     *
     * @mbggenerated
     */
    public Short getAddPun() {
        return addPun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.ADD_PUN
     *
     * @param addPun the value for t_discipline_tf.ADD_PUN
     *
     * @mbggenerated
     */
    public void setAddPun(Short addPun) {
        this.addPun = addPun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.ADD_PUN_PENALTY
     *
     * @return the value of t_discipline_tf.ADD_PUN_PENALTY
     *
     * @mbggenerated
     */
    public BigDecimal getAddPunPenalty() {
        return addPunPenalty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.ADD_PUN_PENALTY
     *
     * @param addPunPenalty the value for t_discipline_tf.ADD_PUN_PENALTY
     *
     * @mbggenerated
     */
    public void setAddPunPenalty(BigDecimal addPunPenalty) {
        this.addPunPenalty = addPunPenalty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.SINGLE_NO
     *
     * @return the value of t_discipline_tf.SINGLE_NO
     *
     * @mbggenerated
     */
    public String getSingleNo() {
        return singleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.SINGLE_NO
     *
     * @param singleNo the value for t_discipline_tf.SINGLE_NO
     *
     * @mbggenerated
     */
    public void setSingleNo(String singleNo) {
        this.singleNo = singleNo == null ? null : singleNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.IS_DETECTION
     *
     * @return the value of t_discipline_tf.IS_DETECTION
     *
     * @mbggenerated
     */
    public String getIsDetection() {
        return isDetection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.IS_DETECTION
     *
     * @param isDetection the value for t_discipline_tf.IS_DETECTION
     *
     * @mbggenerated
     */
    public void setIsDetection(String isDetection) {
        this.isDetection = isDetection == null ? null : isDetection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.DETECTION_ID
     *
     * @return the value of t_discipline_tf.DETECTION_ID
     *
     * @mbggenerated
     */
    public String getDetectionId() {
        return detectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.DETECTION_ID
     *
     * @param detectionId the value for t_discipline_tf.DETECTION_ID
     *
     * @mbggenerated
     */
    public void setDetectionId(String detectionId) {
        this.detectionId = detectionId == null ? null : detectionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.REG_ADDR
     *
     * @return the value of t_discipline_tf.REG_ADDR
     *
     * @mbggenerated
     */
    public String getRegAddr() {
        return regAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.REG_ADDR
     *
     * @param regAddr the value for t_discipline_tf.REG_ADDR
     *
     * @mbggenerated
     */
    public void setRegAddr(String regAddr) {
        this.regAddr = regAddr == null ? null : regAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.BUS_ADDR
     *
     * @return the value of t_discipline_tf.BUS_ADDR
     *
     * @mbggenerated
     */
    public String getBusAddr() {
        return busAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.BUS_ADDR
     *
     * @param busAddr the value for t_discipline_tf.BUS_ADDR
     *
     * @mbggenerated
     */
    public void setBusAddr(String busAddr) {
        this.busAddr = busAddr == null ? null : busAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.DIS_NAME
     *
     * @return the value of t_discipline_tf.DIS_NAME
     *
     * @mbggenerated
     */
    public String getDisName() {
        return disName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.DIS_NAME
     *
     * @param disName the value for t_discipline_tf.DIS_NAME
     *
     * @mbggenerated
     */
    public void setDisName(String disName) {
        this.disName = disName == null ? null : disName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline_tf.PUNISHIMENTBASIS
     *
     * @return the value of t_discipline_tf.PUNISHIMENTBASIS
     *
     * @mbggenerated
     */
    public String getPunishimentbasis() {
        return punishimentbasis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline_tf.PUNISHIMENTBASIS
     *
     * @param punishimentbasis the value for t_discipline_tf.PUNISHIMENTBASIS
     *
     * @mbggenerated
     */
    public void setPunishimentbasis(String punishimentbasis) {
        this.punishimentbasis = punishimentbasis == null ? null : punishimentbasis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discipline_tf
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", compNo=").append(compNo);
        sb.append(", compId=").append(compId);
        sb.append(", compName=").append(compName);
        sb.append(", busPcode=").append(busPcode);
        sb.append(", busCcode=").append(busCcode);
        sb.append(", busAcode=").append(busAcode);
        sb.append(", busTcode=").append(busTcode);
        sb.append(", ocode=").append(ocode);
        sb.append(", economicCode=").append(economicCode);
        sb.append(", principal=").append(principal);
        sb.append(", cardType=").append(cardType);
        sb.append(", idcard=").append(idcard);
        sb.append(", disId=").append(disId);
        sb.append(", reportNum=").append(reportNum);
        sb.append(", specialtyPrimary=").append(specialtyPrimary);
        sb.append(", specialtySecondary=").append(specialtySecondary);
        sb.append(", spePri=").append(spePri);
        sb.append(", disciplineSource=").append(disciplineSource);
        sb.append(", isRegular=").append(isRegular);
        sb.append(", regularId=").append(regularId);
        sb.append(", punishimentprocedure=").append(punishimentprocedure);
        sb.append(", hearing=").append(hearing);
        sb.append(", recordDate=").append(recordDate);
        sb.append(", decisionDate=").append(decisionDate);
        sb.append(", documentNo=").append(documentNo);
        sb.append(", licRegion=").append(licRegion);
        sb.append(", licUalscxax=").append(licUalscxax);
        sb.append(", licSpe=").append(licSpe);
        sb.append(", licYear=").append(licYear);
        sb.append(", licNum=").append(licNum);
        sb.append(", allowOrg=").append(allowOrg);
        sb.append(", allowSupOrg=").append(allowSupOrg);
        sb.append(", aReview=").append(aReview);
        sb.append(", aReviewDate=").append(aReviewDate);
        sb.append(", aLitigation=").append(aLitigation);
        sb.append(", aLitigationDate=").append(aLitigationDate);
        sb.append(", unpunish=").append(unpunish);
        sb.append(", fixedPlace=").append(fixedPlace);
        sb.append(", punishedTimes=").append(punishedTimes);
        sb.append(", controlTimes=").append(controlTimes);
        sb.append(", performStatus=").append(performStatus);
        sb.append(", performResult=").append(performResult);
        sb.append(", actualPenalty=").append(actualPenalty);
        sb.append(", closedDate=").append(closedDate);
        sb.append(", noLicense=").append(noLicense);
        sb.append(", dataType=").append(dataType);
        sb.append(", isAlter=").append(isAlter);
        sb.append(", rOrgcode=").append(rOrgcode);
        sb.append(", rOrgname=").append(rOrgname);
        sb.append(", rHead=").append(rHead);
        sb.append(", rDeptname=").append(rDeptname);
        sb.append(", rDeptcode=").append(rDeptcode);
        sb.append(", rName=").append(rName);
        sb.append(", rId=").append(rId);
        sb.append(", rDate=").append(rDate);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", deleteTime=").append(deleteTime);
        sb.append(", auditUserid=").append(auditUserid);
        sb.append(", auditUsername=").append(auditUsername);
        sb.append(", auditTime=").append(auditTime);
        sb.append(", lastUserid=").append(lastUserid);
        sb.append(", lastUsername=").append(lastUsername);
        sb.append(", tranState=").append(tranState);
        sb.append(", transfer=").append(transfer);
        sb.append(", creditCode=").append(creditCode);
        sb.append(", addPun=").append(addPun);
        sb.append(", addPunPenalty=").append(addPunPenalty);
        sb.append(", singleNo=").append(singleNo);
        sb.append(", isDetection=").append(isDetection);
        sb.append(", detectionId=").append(detectionId);
        sb.append(", regAddr=").append(regAddr);
        sb.append(", busAddr=").append(busAddr);
        sb.append(", disName=").append(disName);
        sb.append(", punishimentbasis=").append(punishimentbasis);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}
