package com.bupt.recommender.mapper;

import com.bupt.recommender.entity.LawCasePunishedPO;

import java.util.List;

public interface LawCasePunishedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discipline_punished_tf
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discipline_punished_tf
     *
     * @mbggenerated
     */
    int insert(LawCasePunishedPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discipline_punished_tf
     *
     * @mbggenerated
     */
    LawCasePunishedPO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discipline_punished_tf
     *
     * @mbggenerated
     */
    List<LawCasePunishedPO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discipline_punished_tf
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LawCasePunishedPO record);

    List<LawCasePunishedPO> selectByCaseId(String caseId);
}