package com.bupt.recommender.mapper;

import com.bupt.recommender.entity.LawCasePO;

import java.util.List;

public interface LawCaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discipline_tf
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discipline_tf
     *
     * @mbggenerated
     */
    int insert(LawCasePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discipline_tf
     *
     * @mbggenerated
     */
    LawCasePO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discipline_tf
     *
     * @mbggenerated
     */
    List<LawCasePO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discipline_tf
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LawCasePO record);
}